# tasks/main.yml

- name: Add repository base
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://cdn.redhat.com/content/dist/rhel8/$releasever/x86_64/baseos/os

- name: Add repository app
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://cdn.redhat.com/content/dist/rhel8/$releasever/x86_64/appstream/os

- name: Add repository app
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm

- name: Install Common useful tools
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - epel-devel
  - autoconf
  - automake
  - make
  - strace
  - openssl-devel
  - gnutls-utils
  - unzip
  - bzip2
  - tar
  - gzip
  - wget
  - ncurses-devel
  - texinfo
  - svn
  - python-devel
  - lua
  # - ninja-build
  - pkgconfig
  # - uuid-devel
  - libuuid
  - libuuid-devel
  # jansson-devel is needed to compile emacs with native json support
  - jansson-devel
  # when: ansible_os_family == "Centos"
  # inotify-tools is needed for rebar3_auto plugin
  - inotify-tools-devel
