# tasks/main.yml

- name: Install Common useful tools
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - autoconf
  - automake
  - make
  - strace
  - openssl-devel
  - gnutls-utils
  - unzip
  - bzip2
  - tar
  - gzip
  - wget
  - ncurses-devel
  - texinfo
  - svn
  - python-devel
  - lua
  # - ninja-build
  - pkgconfig
  # - uuid-devel
  - libuuid
  - libuuid-devel
  # when: ansible_os_family == "Centos"
