# tasks/main.yml

- name: Add repository
  yum_repository:
    name: codeReady
    description: Red Hat CodeReady Linux Builder for RHEL 8 x86_64 (RPMs)
    baseurl: https://satellite.mumble/mumble/content/dist/rhel8/$releasever/x86_64/codeready-builder/os

- name: Install Common useful tools
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - autoconf
  - automake
  - make
  - strace
  - openssl-devel
  - gnutls-utils
  - unzip
  - bzip2
  - tar
  - gzip
  - wget
  - ncurses-devel
  - texinfo
  - svn
  - python-devel
  - lua
  # - ninja-build
  - pkgconfig
  # - uuid-devel
  - libuuid
  - libuuid-devel
  # jansson-devel is needed to compile emacs with native json support
  - jansson-devel
  # when: ansible_os_family == "Centos"
  # inotify-tools is needed for rebar3_auto plugin
  - inotify-tools-devel
