# tasks/main.yml

- name: Add multiple repositories into the same file (1/2)
  yum_repository:
    name: epel
    description: EPEL YUM repo
    file: external_repos
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no

- name: Install Common useful tools
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - autoconf
  - automake
  - make
  - strace
  - openssl-devel
  - gnutls-utils
  - unzip
  - bzip2
  - tar
  - gzip
  - wget
  - ncurses-devel
  # - texinfo
  - svn
  - python3
  - lua
  # - ninja-build
  - pkgconfig
  # - uuid-devel
  # - libuuid
  - libuuid-devel
  # jansson-devel is needed to compile emacs with native json support
  - jansson-devel
  # when: ansible_os_family == "Centos"
  # inotify-tools is needed for rebar3_auto plugin
  - inotify-tools-devel

- name: Remove repository from a specific repo file
  yum_repository:
    name: epel
    file: external_repos
    state: absent
