# tasks/main.yml

- name: Install build tools
  yum:
    name: "@Development tools"
    state: present
  become: yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 8) or ansible_distribution == "Amazon"

- name: Install Common useful tools Centos
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - make
  - glibc-devel
  - gcc
  - patch
  - openssl-devel
  - gdb
  - emacs
  - unzip
  - tar
  - rsync
  - strace
  - git
  - tmux
  - cmake
  - pkg-config
  - cmake-data
  - jsoncpp-devel
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 8) or ansible_distribution == "Amazon"

- name: Install Common useful tools Ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - build-essential
  - make
  - glibc-source
  - gcc
  - patch
  - openssl-dev
  - gdb
  - emacs
  - unzip
  - tar
  - rsync
  - strace
  - git
  - tmux
  - cmake
  - pkg-config
  - cmake-data
  - libjsoncpp-dev

  # - autoconf
  # - automake
  # - make
  # - strace
  # - openssl-dev
  # - gnutls-utils
  # # diffutils needed to compile gcc
  # - diffutils
  # # procps-ng s for sysctl
  # # - procps-ng
  # - unzip
  # - bzip2
  # - tar
  # - gzip
  # - wget
  # - ncurses-dev
  # - texinfo
  # - svn
  # - net-tools
  # - netcat
  # - htop
  # - git
  # install ping, etc
  # - iputils
  # # sysctl - used for kernel panic dumps
  # - procps-ng
  # # python is used by GDB is compilied with python support
  # - python2-dev
  # - lua
  # - rsync
  # - tmux
  # - ninja-build
  # # - uuid-devel
  # # - libuuid
  # - libuuid-dev
  # # jansson-devel is needed to compile emacs with native json support
  # - jansson-dev
  # # inotify-tools is needed for rebar3_auto plugin
  # - inotify-tools
  # # gmp-devel used by GDB
  # - gmp-devel
  # # llvm/gcc/boost to avoid long build times
  # - gcc-toolset-10-gcc
  # - llvm-toolset
  # - clang-tools-extra
  # - boost-devel
  # - cmake
  #   # used by cmake
  # - pkg-config
  # - cmake-data
  #  - nano
  # # deps for binance api
  # - gcc-9
  # - g++-9
  # - libwebsockets-dev
  # - libcurl4-openssl-dev
  # - libjsoncpp-dev
  # - libmbedtls-dev
  when: ansible_distribution == "Ubuntu"
