# tasks/main.yml

- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: Add multiple repositories into the same file (2/2)
  yum_repository:
    name: rpmforge
    description: RPMforge YUM repo
    file: external_repos
    baseurl: http://apt.sw.be/redhat/el7/en/$basearch/rpmforge
    mirrorlist: http://mirrorlist.repoforge.org/el7/mirrors-rpmforge
    enabled: no

- name: Install Common useful tools
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - autoconf
  - automake
  - make
  - strace
  - openssl-devel
  - gnutls-utils
  - unzip
  - bzip2
  - tar
  - gzip
  - wget
  - ncurses-devel
  - texinfo
  - svn
  - python-devel
  - lua
  # - ninja-build
  - pkgconfig
  # - uuid-devel
  - libuuid
  - libuuid-devel
  # jansson-devel is needed to compile emacs with native json support
  - jansson-devel
  # when: ansible_os_family == "Centos"
  # inotify-tools is needed for rebar3_auto plugin
  - inotify-tools
