# tasks/main.yml


  # - rpm_key:
  #     state: present
  #     key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
    disable_gpg_check: yes
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
  # when: not epel_repofile_result.stat.exists

- name: Install DNF config-manager
  yum:
    name: dnf-plugins-core
    state: present

- name: enable PowerTools repository
  command:
    cmd: dnf config-manager --enable powertools
    warn: false
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 8) or ansible_distribution == "Rocky"

- name: Install Common useful tools
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - epel-release
  - autoconf
  - automake
  - make
  - strace
  - openssl-devel
  - gnutls-utils
  # diffutils needed to compile gcc
  - diffutils
  # procps-ng s for sysctl
  # - procps-ng
  - unzip
  - bzip2
  - tar
  - gzip
  - wget
  - ncurses-devel
  - texinfo
  - svn
  - net-tools
  - netcat
  - htop
  - git
  # install ping, etc
  - iputils
  # sysctl - used for kernel panic dumps
  - procps-ng
  # python is used by GDB is compilied with python support
  - python2-devel
  - lua
  - rsync
  - tmux
  # - ninja-build
  - pkgconfig
  # - uuid-devel
  # - libuuid
  - libuuid-devel
  # jansson-devel is needed to compile emacs with native json support
  - jansson-devel
  # inotify-tools is needed for rebar3_auto plugin
  - inotify-tools
  # gmp-devel used by GDB
  - gmp-devel
  # llvm/gcc/boost to avoid long build times
  - gcc-toolset-10-gcc
  - llvm-toolset
  - clang-tools-extra
  - boost-devel
  - cmake
  # deps for binance api
  - libcurl-devel
  - jsoncpp-devel
  - libwebsockets-devel
  - nano
  - mbedtls-devel

# - name: Remove repository from a specific repo file
#   yum_repository:
#     name: epel
#     file: external_repos
#     state: absent
