# tasks/main.yml

- name: Add repository
  yum_repository:
    name: epel
    description: EPEL
    baseurl: https://centos.pkgs.org/8/epel-x86_64/

- name: Install Common useful tools
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - autoconf
  - automake
  - make
  - strace
  - openssl-devel
  - gnutls-utils
  - unzip
  - bzip2
  - tar
  - gzip
  - wget
  - ncurses-devel
  # - texinfo
  - svn
  - python3
  - lua
  # - ninja-build
  - pkgconfig
  # - uuid-devel
  # - libuuid
  - libuuid-devel
  # jansson-devel is needed to compile emacs with native json support
  - jansson-devel
  # when: ansible_os_family == "Centos"
  # inotify-tools is needed for rebar3_auto plugin
  - inotify-tools-devel
