# tasks/main.yml

- name: Install Common useful tools
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - make
  - htop
  - strace
  - openssl-devel
  - unzip
  - tar
  - gzip
  - wget
  - ncurses-devel
  - texinfo
  - svn
  - python-devel
  # when: ansible_os_family == "Centos"
