# tasks/main.yml

- name: Install build tools
  yum:
    name: "@Development tools"
    state: present
  become: yes
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 8) or ansible_distribution == "Amazon"

- name: Install Common useful tools Centos
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - make
  - glibc-devel
  - gcc
  - patch
  - openssl-devel
  - gdb
  - emacs
  - unzip
  - tar
  - rsync
  - strace
  - git
  - tmux
  - cmake
  - pkg-config
  - cmake-data
  - jsoncpp-devel
  - readline-devel
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 8) or ansible_distribution == "Amazon"

- name: Install Common useful tools Ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - build-essential
  - make
  - glibc-source
  - gcc
  - patch
  - openssl
  - libssl-dev
  - gdb
  - emacs
  - unzip
  - tar
  - rsync
  - strace
  - git
  - tmux
  - cmake
  - pkg-config
  - cmake-data
  - libjsoncpp-dev
  - libreadline-dev
  when: ansible_distribution == "Ubuntu"

# ubuntu installs jsoncpp into non-standard location
- name: Create symbolic link for jsoncpp
  file:
    src: "/usr/include/jsoncpp/json"
    dest: "/usr/include/json"
    state: link
  when: ansible_distribution == "Ubuntu"
